config/routes.rb
Rails.application.routes.draw do
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

# 顧客用

scope module: :public do
	root to:"homes#top"
  get "about"=>"homes#about",as:"about"

end

scope module: :public do
  resources:products,only: [:index,:show]
  get "searches"=>"products#searches"
  get "search_word" => "products#search_word"

end

scope module: :public do
  get 'customers/my_page' => 'customers#show'
  get 'customers/information/edit' => 'customers#edit'
  patch 'customers/information' => 'customers#update'


  get "customers/unsubscribe"=>"customers#unsubscribe",as:"unsubscribe"
  patch "customers/withdrawal"=>"customers#withdrawal",as:"withdrawal"
end
scope module: :public do
  resources:cart_items,only: [:index,:update,:destroy,:create] do
  delete "cart_items/destroy_all"=>"cart_items#destroy_all",as:"destroy_all"
  end
end

scope module: :public do
  resources:orders,only: [:new,:create,:index]
  post "orders/confirm"=>"orders#confirm",as:"confirm"
  get "orders/complete"=>"orders#complete",as:"complete"
  get "orders/:id"=>"orders#show",as:"order"
end

scope module: :public do
  resources:shipping_addresses
end

# 管理者用
namespace :admin do
  root to:'homes#top'

  resources:products

  resources:genres,only: [:index,:create,:edit,:update]

  resources:customers,only: [:index,:show,:edit,:update]

  resources:orders,only: [:show,:update]

  resources:order_details,only: [:update]
end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :post_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  has_many :shipping_addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  def active_for_authentication?
    super && (is_deleted==false)
  end

  def address_display
    '〒  '+post_code+'  '+address+'  '+last_name+'  '+first_name
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
    before_action :authenticate_admin!
  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])

  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer)
    else
      # redirect_to request.referer
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :post_code, :address, :phone_number, :email, :is_deleted)
  end


end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 my-3">
      <% if @customer.errors.any? %>
        <%= @customer.errors.count %>件のエラーが発生しました。
        <ul>
          <% @customer.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>

      <h3 class="mt-2"><%= @customer.last_name %> <%= @customer.first_name %>さんの会員情報編集</h3>
      <%= form_with model: @customer, url: admin_customer_path(@customer), method: :patch do |f| %>
      <table class="table table-borderless offset-2">
        <tbody>
          <tr>
            <th>会員id</th>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <th>氏名</th>
            <td><%= f.text_field :last_name, class:'form-control' %></td>
            <td><%= f.text_field :first_name, class:'form-control' %></td>
          </tr>
          <tr>
      　　  　<th>フリガナ</th>
      　　　　<td><%= f.text_field :last_name_kana, class:'form-control' %></td>
      　　　　<td><%= f.text_field :first_name_kana, class:'form-control' %></td>
          </tr>
          <tr>
            <th>郵便番号</th>
            <td><%= f.text_field :post_code, class:'form-control' %></td>
          </tr>
          <tr>
            <th>住所</th>
            <td><%= f.text_field :address, class:'form-control' %></td>
          </tr>
          <tr>
            <th>電話番号</th>
            <td><%= f.text_field :phone_number, class:'form-control' %></td>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <td><%= f.text_field :email, class:'form-control' %></td>
          </tr>
          <tr>
            <th>会員ステータス</th>
            <td>
             <%= f.radio_button :is_deleted, false %>
             <%= f.label :is_deleted, "有効", value: false %>
             <%= f.radio_button :is_deleted, true %>
             <%= f.label :is_deleted, "退会", value: true %>
            </td>
          </tr>
        </tbody>
      </table>
      <div class="form-group col-md-2 offset-5">
        <%= f.submit "変更を保存", class:'btn btn-success  inline-block px-4' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
   <div class="col-sm-12 col-md-11 col-lg-8 px-5 px-sm-0 mx-auto my-3" >
    <h3 class="mb-3">会員一覧</h3>
     <table class='table table-hover'>
      <thead>
        <tr class="table-active">
        <th>会員ID</th>
         <th>氏名</th>
         <th>メールアドレス</th>
         <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
       <% @customers.each do |customer| %>
        <tr>
          <td><%=  customer.id %></td>
          <td><%= link_to customer.last_name, admin_customer_path(customer) %><%= link_to customer.first_name, admin_customer_path(customer) %></td>
          <td><%= customer.email %></td>
          <td>
           <% if customer.is_deleted %>
           <p class="text-muted font-weight-bold">退会</p>
           <% else %>
           <P class="text-success font-weight-bold">有効</P>
           <% end %>
           </td>
        </tr>
        <% end %>
      </tbody>
     </table>
   </div>
   <div class="col-5 offset-4"><%= paginate @customers, theme: 'bootstrap-5' %></div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 my-3 offset-2">
      <h3><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h3>
      <table class="table table-borderless">
        <tbody>
          <tr>
            <th style="width: 150px">会員ID</th>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <th style="width: 150px">氏名</th>
            <td><%= @customer.last_name %> <%= @customer.first_name %></td>
          </tr>
          <tr>
    　　  　<th style="width: 150px">フリガナ</th>
    　　　　<td><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
          </tr>
          <tr>
            <th style="width: 150px">郵便番号</th>
            <td><%= @customer.post_code %></td>
          </tr>
          <tr>
            <th style="width: 150px">住所</th>
            <td><%= @customer.address %></td>
          </tr>
          <tr>
            <th style="width: 150px">電話番号</th>
            <td><%= @customer.phone_number %></td>
          </tr>
          <tr>
            <th style="width: 150px">メールアドレス</th>
            <td><%= @customer.email %></td>
          </tr>
          <tr>
            <th style="width: 150px" class="align-middle">会員ステータス</th>
            <td>
              <% if @customer.is_deleted %>
               <p class="text-muted font-weight-bold align-middle">退会</p>
              <% else %>
              <P class="text-success font-weight-bold">有効</P>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
        <div class="offset-md-3">
          <%= link_to "編集する", edit_admin_customer_path(@customer.id), class: "btn btn-success mr-5 inline-block" %>
          <%= link_to "注文履歴一覧を見る", admin_root_path, class: "btn btn-primary me-auto inline-block" %>
        </div>
    </div>

  </div>
</div>