config/routes.rb
Rails.application.routes.draw do
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

# 顧客用

scope module: :public do
	root to:"homes#top"
  get "about"=>"homes#about",as:"about"

end

scope module: :public do
  resources:products,only: [:index,:show]
  get "searches"=>"products#searches"
  get "search_word" => "products#search_word"

end

scope module: :public do
  get 'customers/my_page' => 'customers#show'
  get 'customers/information/edit' => 'customers#edit'
  patch 'customers/information' => 'customers#update'


  get "customers/unsubscribe"=>"customers#unsubscribe",as:"unsubscribe"
  patch "customers/withdrawal"=>"customers#withdrawal",as:"withdrawal"
end
scope module: :public do
  resources:cart_items,only: [:index,:update,:destroy,:create] do
  delete "cart_items/destroy_all"=>"cart_items#destroy_all",as:"destroy_all"
  end
end

scope module: :public do
  resources:orders,only: [:new,:create,:index]
  post "orders/confirm"=>"orders#confirm",as:"confirm"
  get "orders/complete"=>"orders#complete",as:"complete"
  get "orders/:id"=>"orders#show",as:"order"
end

scope module: :public do
  resources:shipping_addresses
end

# 管理者用
namespace :admin do
  root to:'homes#top'

  resources:products

  resources:genres,only: [:index,:create,:edit,:update]

  resources:customers,only: [:index,:show,:edit,:update]

  resources:orders,only: [:show,:update]

  resources:order_details,only: [:update]
end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum method_of_payment: {credit_card: 0, transfer: 1}
  enum order_status: {waiting: 0, confirmation: 1, production: 2, preparing: 3 , shipped: 4}

  def address_display
    '〒' + post_code + ' ' + address + ' ' + name
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
   #管理者以外には処理してほしくないので、最初にadminかどうかを確認
  
  def show
    
    @order = Order.find(params[:id])
    @orders = Order.all
    @order_details = OrderDetail.where(order_id: @order.id)
    @order_new = Order.new
    @order_detail = OrderDetail.find(params[:id])
    
    @order_status_key = Order.order_statuses_i18n.invert
    @making_status_key = OrderDetail.making_statuses_i18n.invert
    @customer = @order.customer
  end
  
  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if @order.order_status == "confirmation"
      @order.order_details.update(making_status: 1)
    end
    redirect_to request.referer
  end


  private

  def order_params
    params.require(:order).permit(:order_status)
  end
  
end




 

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8">
      <h3 class="m-3">注文履歴詳細</h3>
       <table class="table table-hover">
        <tbody>
          <tr>
            <th>購入者</th>
            <td>
            <%= link_to admin_customer_path(@customer) do %>
              <%= @customer.last_name %>
              <%= @customer.first_name %>
            <% end %>
            </td>
          </tr>
          <tr>
            <th>注文日</th>
            <td><%= l @order_detail.created_at, format: :short %></td>
          </tr>
          <tr>
            <th>配送先</td>
            <td>〒<%= @order.post_code %> <%= @order.address %><br>
                <%= @order.name %>
            </td>
          </tr>
          <tr>
            <th>支払方法</th>
            <td><%= Order.method_of_payments_i18n[@order.method_of_payment] %></td>
          </tr>
          <tr>
            <th>注文ステータス</th>
            <td>
             <%= form_with model: @order, url: admin_order_path(@order), method: :patch do |f| %>
             <%= f.select :order_status, @order_status_key, {prompt: "選択してください"} %>
             <%= f.submit "更新", class: "btn btn-success  inline-block ml-3" %>
             <% end %>
            </td>
           <!--決められたものはcollection_selectで使うことができない-->
          </tr>
        </tbody>
       </table>
       <table class='table'>
         <thead>
           <tr class="table-active">
            <th>商品名</th>
            <th>単価 (税込)</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
           </tr>
         </thead>
         <tbody>
           <% @order_details.each do |order_detail| %>
           <tr>
              <td><%= order_detail.product.name %></td>
              <td><%= (order_detail.product.price * 1.1).floor %></td>
              <td><%= order_detail.quantity %></td>
              <td><% subtotal = ((order_detail.product.price*order_detail.quantity)*1.1).to_i %>
              <%= subtotal %>
              </td>
              <td>
              <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), method: :patch do |f| %>
                <%= f.select :making_status, @making_status_key, {prompt: "選択してください"} %>
                <%= f.submit "更新", class: "btn btn-success  inline-block ml-3" %>
              <% end %>
               </td>
           </tr>
           <% end %>
         </tbody>
       </table>
    </div>
    <div class="col-lg-4 mt-5">
      <table class="table table-hover">
        <tbody>
          <% total = 0 %>
          <tr>
            <th>商品合計</th>
            <td>
              <% @order_details.each do |order_detail| %>
                <% subtotal = ((order_detail.product.price*order_detail.quantity)*1.1).to_i %>
                <% total += subtotal %>
              <% end %>
              <%= total %>
            </td>
          </tr>
          <tr>
            <th>送料</th>
            <td>
              <% @order_new.postage = 800 %>
              <%= @order_new.postage %>
            </td>
          </tr>
          <tr>
            <th>請求金額合計</th>
            <td>
              <% @order_new.total_payment = @order.postage + total.to_i %>
              <%= @order_new.total_payment %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>