config/routes.rb
Rails.application.routes.draw do
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

# 顧客用

scope module: :public do
	root to:"homes#top"
  get "about"=>"homes#about",as:"about"

end

scope module: :public do
  resources:products,only: [:index,:show]
  get "searches"=>"products#searches"
  get "search_word" => "products#search_word"

end

scope module: :public do
  get 'customers/my_page' => 'customers#show'
  get 'customers/information/edit' => 'customers#edit'
  patch 'customers/information' => 'customers#update'


  get "customers/unsubscribe"=>"customers#unsubscribe",as:"unsubscribe"
  patch "customers/withdrawal"=>"customers#withdrawal",as:"withdrawal"
end
scope module: :public do
  resources:cart_items,only: [:index,:update,:destroy,:create] do
  delete "cart_items/destroy_all"=>"cart_items#destroy_all",as:"destroy_all"
  end
end

scope module: :public do
  resources:orders,only: [:new,:create,:index]
  post "orders/confirm"=>"orders#confirm",as:"confirm"
  get "orders/complete"=>"orders#complete",as:"complete"
  get "orders/:id"=>"orders#show",as:"order"
end

scope module: :public do
  resources:shipping_addresses
end

# 管理者用
namespace :admin do
  root to:'homes#top'

  resources:products

  resources:genres,only: [:index,:create,:edit,:update]

  resources:customers,only: [:index,:show,:edit,:update]

  resources:orders,only: [:show,:update]

  resources:order_details,only: [:update]
end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :cart_items
  has_many :order_details
  belongs_to :genre

  has_one_attached :product_image

  validates :price, presence: true
  validates :product_image, presence: true

  def get_product_image
    unless product_image.attached?
      file_path=Rails.root.join('app/assets/images/no_cake_image.jpg')
      product_image.attach(io:File.open(file_path),filename:'default-image.jpg',content_type:'image/jpeg')
    end
    product_image
  end

  def with_tax_price
    tax = 1.1
    (price*tax).floor
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

  def index
    @products = Product.page(params[:page])
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_product_path(@product)
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    product = Product.find(params[:id])
    product.update(product_params)
    redirect_to admin_product_path(product)
  end

  private

  def product_params
    params.require(:product).permit(:genre_id, :is_active, :name, :description, :price, :product_image)
  end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/_index.html.erb
<table class='table'>
  <thead class="table table-secondary">
    <tr>
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
    </tr>
  </thead>
  <tbody>
    <!--ここからデータ読み込み-->
    <% products.each do |product| %>
    <tr>
      <!--商品ID-->
      <td class="align-middle"><p class="m-0"><%= product.id %></p></td>
      <!--商品名-->
      <td class="align-middle"><p class="m-0"><%= link_to product.name, admin_product_path(product.id) %></p></td>
      <!--税抜価格-->
      <td class="align-middle"><p class="m-0"><%= product.price %></p></td>
      <!--ジャンル-->
      <td class="align-middle"><p class="m-0"><%= product.genre.genre %></p></td>
      <!--販売ステータス-->
      <td class="align-middle">
        <% if product.is_active %>
          <P class="text-success m-0 font-weight-bold">販売中</P>
        <% else %>
          <p class="m-0">販売停止中</p>
        <% end %>
      </td>
    </tr>
    <% end %>
    <!--ここまで-->
  </tbody>
</table>

<!--ページネーション～kaminari～-->
<div class="col-2 offset-5">
  <%= paginate @products, theme: 'bootstrap-5' %>
</div>

app/views/admin/products/edit.html.erb
<div class="container">
  <div class="row mt-4">

    <h2>商品編集</h2>
    <div class="col-md-8 mt-4">
      <table class="table table-borderless">
        <%= form_with model: @product, url: admin_product_path(@product.id), method: :patch, local:true do |f| %>
          <tr>
            <td>商品画像</td>
            <td><%= f.file_field :product_image, accept: "image/*" %></td>
          </tr>
          <tr>
            <td>商品名</td>
            <td><%= f.text_field :name, size: "30" %></td>
          </tr>
          <tr>
            <td>商品説明</td>
            <td><%= f.text_area :description, size: "32x5" %></td>
          </tr>
          <tr>
            <td>ジャンル</td>
            <td><%= f.collection_select :genre_id, Genre.all, :id, :genre, include_blank: "選択してください" %></td>
          </tr>
          <tr>
            <td>税抜き価格</td>
            <td><%= f.text_field :price %>円</td>
          </tr>
          <tr>
            <td>販売ステータス</td>
            <td>
              <%= f.radio_button :is_active, 'true' %>販売中
              <%= f.radio_button :is_active, 'false' %>販売停止中
            </td>
          </tr>
          <tr>
            <td></td>
            <td><%= f.submit '変更を保存', class:"btn btn-success" %></td>
          </tr>
        <% end %>
        </table>
      </div>

      <!-- %= render 'form', product: @product %-->
    </div>
  </div>
</div>

app/views/admin/products/index.html.erb
<div class="container">
  <div class="mt-4">
    <div class="col-md-auto">

      <div class="row mt-4">
        <div class="col-3">
          <h2>商品一覧</h2>
        </div>
        <div class="col-8 text-right">
          <%= link_to "＋", new_admin_product_path, class:"h1 text-decoration-none text-dark", 'data-turbolinks': false  %>
        </div>
      </div>

      <div class="col-12 mt-4 mb-5">
      <%= render 'index', products: @products %>
      </div>

    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class="container">
  <div class="row mt-4">

    <h2>商品新規登録</h2>
    <div class="col-md-6 mt-4">
      <table class="table table-borderless">
        <!--バリデーションエラーメッセージ-->
        <% if @product.errors.any? %>
          <tr>
            <td></td>
            <td>
              <%= @product.errors.count %>件のエラーが発生しました
              <ul class="list-group list-unstyled">
                <% @product.errors.full_messages.each do |message| %>
                  <li class="text-danger"><%= message %></li>
                <% end %>
              </ul>
            </td>
          </tr>
        <% end %>
        <!--登録フォーム-->
        <%= form_with model: @product, url: admin_products_path, local:true do |f| %>
          <tr>
            <td>商品画像</td>
            <td><%= f.file_field :product_image, accept: "image/*" %></td>
          </tr>
          <tr>
            <td>商品名</td>
            <td><%= f.text_field :name, size: "30" %></td>
          </tr>
          <tr>
            <td>商品説明</td>
            <td><%= f.text_area :description, size: "32x5" %></td>
          </tr>
          <tr>
            <td>ジャンル</td>
            <td><%= f.collection_select :genre_id, Genre.all, :id, :genre, include_blank: "選択してください" %></td>
          </tr>
          <tr>
            <td>税抜価格</td>
            <td><%= f.number_field :price %>円</td>
          </tr>
          <tr>
            <td>販売ステータス</td>
            <td>
              <%= f.radio_button :is_active, 'true' %>販売中
              <%= f.radio_button :is_active, 'false' %>販売停止中
            </td>
          </tr>
          <tr>
            <td></td>
            <td><%= f.submit '新規投稿', class:"btn btn-success" %></td>
          </tr>
        <% end %>
      </table>
    </div>

  </div>
</div>

app/views/admin/products/show.html.erb
<div class="container">
  <!--<div class="row">-->
    <div class="mt-4">
      <h2>商品詳細</h2>
      <!--商品詳細データ-->
      <div class="row mt-4">
        <!--商品画像-->
        <div class="col-md-4">
          <%= image_tag @product.product_image, size:"320x240" %>
        </div>
        <div class="col-md-7">
          <table class='table table-borderless'>
            <tr>
              <td>商品名</td>
              <td><%= @product.name %></td >
            </tr>
            <tr>
              <td class="align-middle">商品説明</td>
              <td><%= @product.description %></td>
            </tr>
            <tr>
              <td>ジャンル</td>
              <td><%= @product.genre.genre %></td>
            </tr>
            <tr>
              <td> 税込価格<br />(税抜価格)</td>
              <td class="align-middle"><%= (@product.price*1.1).round.to_s(:delimited) %>（<%= @product.price.to_s(:delimited) %>）円</td>
            </tr>
            <tr>
              <td>販売ステータス</td>
              <td>
                <% if @product.is_active %>
                  <P class="text-success  font-weight-bold">販売中</P>
                <% else %>
                  <p>販売停止中</p>
                <% end %>
              </td>
            </tr>
            <tr>
              <td></td>
              <td><%= link_to "編集する", edit_admin_product_path(@product.id) ,class: "btn btn-success", 'data-turbolinks': false %></td>
            </tr>
          </table>
        </div>

      </div>
    </div>
  <!--</div>-->
</div>