config/routes.rb
Rails.application.routes.draw do
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

# 顧客用

scope module: :public do
	root to:"homes#top"
  get "about"=>"homes#about",as:"about"

end

scope module: :public do
  resources:products,only: [:index,:show]
  get "searches"=>"products#searches"
  get "search_word" => "products#search_word"

end

scope module: :public do
  get 'customers/my_page' => 'customers#show'
  get 'customers/information/edit' => 'customers#edit'
  patch 'customers/information' => 'customers#update'


  get "customers/unsubscribe"=>"customers#unsubscribe",as:"unsubscribe"
  patch "customers/withdrawal"=>"customers#withdrawal",as:"withdrawal"
end
scope module: :public do
  resources:cart_items,only: [:index,:update,:destroy,:create] do
  delete "cart_items/destroy_all"=>"cart_items#destroy_all",as:"destroy_all"
  end
end

scope module: :public do
  resources:orders,only: [:new,:create,:index]
  post "orders/confirm"=>"orders#confirm",as:"confirm"
  get "orders/complete"=>"orders#complete",as:"complete"
  get "orders/:id"=>"orders#show",as:"order"
end

scope module: :public do
  resources:shipping_addresses
end

# 管理者用
namespace :admin do
  root to:'homes#top'

  resources:products

  resources:genres,only: [:index,:create,:edit,:update]

  resources:customers,only: [:index,:show,:edit,:update]

  resources:orders,only: [:show,:update]

  resources:order_details,only: [:update]
end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def full_name
    self.last_name + " " + self.first_name
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :product

  validates :quantity, presence: true

  def sub_total
    quantity*product.with_tax_price
  end

  def quantity_options
    options = []
    (self.quantity + 11).times do |count|
      options << [count, count]
    end
    return options
  end

  def self.total_price(customer)
    CartItem.where(customer_id: customer.id).inject(0){|sum, cart_item| sum + cart_item.sub_total}
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :post_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  has_many :shipping_addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  def active_for_authentication?
    super && (is_deleted==false)
  end

  def address_display
    '〒  '+post_code+'  '+address+'  '+last_name+'  '+first_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products

  def self.search_for(content)
    genres = Genre.where("genre LIKE?", "#{content}")
    genres.inject(init = []){|result, genre| result + genre.products}
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum method_of_payment: {credit_card: 0, transfer: 1}
  enum order_status: {waiting: 0, confirmation: 1, production: 2, preparing: 3 , shipped: 4}

  def address_display
    '〒' + post_code + ' ' + address + ' ' + name
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product
  enum making_status: {can_not_start: 0, waiting_for_production: 1, production: 2, completed: 3}

  def sub_total
    quantity*product.with_tax_price
  end

  def self.total_price(order)
    OrderDetail.where(order_id: order.id).inject(0){|sum, order_detail| sum + order_detail.sub_total}
  end

end
# 0: 着手不可, 1:製作待ち, 2: 製作中, 3: 製作完了

app/models/product.rb
class Product < ApplicationRecord
  has_many :cart_items
  has_many :order_details
  belongs_to :genre

  has_one_attached :product_image

  validates :price, presence: true
  validates :product_image, presence: true

  def get_product_image
    unless product_image.attached?
      file_path=Rails.root.join('app/assets/images/no_cake_image.jpg')
      product_image.attach(io:File.open(file_path),filename:'default-image.jpg',content_type:'image/jpeg')
    end
    product_image
  end

  def with_tax_price
    tax = 1.1
    (price*tax).floor
  end

end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  belongs_to :customer

  validates :post_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
  validates :phone_number, presence: true

  def address_display
    '〒  '+post_code+'  '+address+'  '+name
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def show
    @genre = Genre.find(params[:id])
  end

  def new
    @genre = Genre.new
  end

  def create
    genre = Genre.new(genre_params)
    if genre.save
      redirect_to admin_genres_path
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    if genre.update(genre_params)
      redirect_to admin_genres_path
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:genre)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders = Order.page(params[:page])
    # @search = Customer.ransack(params[:q])

  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
   #管理者以外には処理してほしくないので、最初にadminかどうかを確認
  
  def show
    
    @order = Order.find(params[:id])
    @orders = Order.all
    @order_details = OrderDetail.where(order_id: @order.id)
    @order_new = Order.new
    @order_detail = OrderDetail.find(params[:id])
    
    @order_status_key = Order.order_statuses_i18n.invert
    @making_status_key = OrderDetail.making_statuses_i18n.invert
    @customer = @order.customer
  end
  
  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if @order.order_status == "confirmation"
      @order.order_details.update(making_status: 1)
    end
    redirect_to request.referer
  end


  private

  def order_params
    params.require(:order).permit(:order_status)
  end
  
end




 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_search
  before_action :configure_permitted_parameters, if: :devise_controller?


 private

  def set_search
    @q = Product.ransack(params[:q])
    @product = @q.result(distinct: true).page(params[:page]).per(8)

  end
#   ransackメソッドは検索ヘルパーメソッドである
# resultメソッドは検索結果を返すヘルパーメソッドである
# distinct: trueは、重複する検索結果を除外する役割を持つ

 protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :post_code, :address, :phone_number])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<footer class="pt-3 bg-secondary bg-dark text-white">
  <div class="container-fluid">
    <div class="row no-gutters">
      <div class="col-md-8">
        <h3 class="fst-italic" style="font-family: Georgia, serif;">長野県にある小さな洋菓子店<br>「ながのCAKE」</h3>
      </div>
      <div class="col-md-4 ">
        <ul class="list-unstyled"  style="text-align: right; cursor: pointer;">
          <li class="mb-2">お店の概要 <i class="fa-sharp fa-solid fa-store"></i><i class="fa-regular fa-cake-slice"></i></li>
          <li class="mb-2">プライバシーポリシー <i class="fa-solid fa-handshake-simple"></i></li>
          <li>新着情報 <i class="fa-solid fa-mug-saucer"></i></li>
        </ul>
        <ul class="list-unstyled mt-2" style="text-align: right; cursor: pointer;">
          <li>Twitter <i class="fa-brands fa-twitter"></i></li>
          <li>Instagram <i class="fa-brands fa-instagram"></i></li>
          <li>FaceBook <i class="fa-brands fa-facebook"></i></li>
          <li>YouTube <i class="fa-brands fa-youtube"></i></li>
        </ul>
      </div>
      <div class="col-md-12 mx-auto text-center">
        <p class="py-2">&copy;NAGANO CAKE ANPANMAN<i class="fa-solid fa-bread-slice"></i></p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="shadow-sm">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark py-3">
    <div class="container-fluid">
        <!--会員用のヘッダー-->
        <% if customer_signed_in? %>
        <a class="navbar" href="/"><%= image_tag('logo.jpg')%></a>
        <h5 class=" m-0 text-white">ようこそ、<%= current_customer.last_name %>さん!</h5>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <li class="mr-2"><%= link_to "マイページ", customers_my_page_path,class: 'nav-link text-white btn btn-outline-secondary' %></li>
            <li class="mr-2"><%= link_to "商品一覧", products_path,class: 'nav-link text-white btn btn-outline-secondary' %></li>
            <li class="mr-2"><%= link_to "カート", cart_items_path,class: 'nav-link text-white btn btn-outline-secondary'  %></li>
            <li class="mr-2"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete,class: 'nav-link text-white btn btn-outline-secondary'  %></li>
          </ul>
          <div><%= render 'layouts/search' %></div>
        </div>
        <!--管理人のヘッダー-->
        <% elsif admin_signed_in? %>
        <a class="navbar" href="/"><%= image_tag('logo.jpg')%></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <li class="mr-2"><%= link_to "商品一覧", admin_products_path, class: 'nav-link text-white btn btn-outline-secondary' %></li>
            <li class="mr-2"><%= link_to "会員一覧", admin_customers_path, class: 'nav-link text-white btn btn-outline-secondary' %></li>
            <li class="mr-2"><%= link_to "注文履歴一覧", admin_root_path, class: 'nav-link text-white btn btn-outline-secondary' %></li>
            <li class="mr-2"><%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link text-white btn btn-outline-secondary' %></li>
            <li class="mr-2"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-white btn btn-outline-secondary' %></li>
          </ul>
          <div><%= render 'layouts/search' %></div>
        </div>
        <% else %>
        <a class="navbar" href="/"><%= image_tag('logo.jpg')%></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <li class="mr-2"><%= link_to "About", about_path,class: 'nav-link text-white btn btn-outline-secondary' %></li>
            <li class="mr-2"><%= link_to "商品一覧", products_path,class: 'nav-link text-white btn btn-outline-secondary' %></li>
            <li class="mr-2"><%= link_to "新規登録", new_customer_registration_path,class: 'nav-link text-white btn btn-outline-secondary' %></li>
            <li class="mr-2"><%= link_to "ログイン", new_customer_session_path,class: 'nav-link text-white btn btn-outline-secondary' %></li>
          </ul>
          <div><%= render 'layouts/search' %></div>
        </div>
        <% end %>
    </div>
  </nav>
</header>

app/views/layouts/_search.html.erb
<!--検索フォーム-->

<%= search_form_for @q, url: search_word_path, class:"search-form" do |f| %>
<%= f.search_field :name_cont, class: "border border-white", placeholder: "検索" %>
<%= f.submit "検索", class:'search-button' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://kit.fontawesome.com/1f364fbf4d.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <main>
      <%= yield %>
    </main>
    <%= render 'layouts/footer'%>
  </body>
</html>